# VPS06 - Cesar Agusto Lopera Maya
vps_name: VPS06
account_holder: "Cesar Agusto Lopera Maya"

agents:
  - name: "VPS06-FundedNext"
    port: 8000
    terminal_path: "{{ mt5_terminals.fundednext }}"
    display_name: "FN - Cesar Agusto Lopera Maya"
    account_holder: "{{ account_holder }}"
    prop_firm: "FN"
    initial_balance: 100000.0

  - name: "VPS06-FivePercent"
    port: 8001
    terminal_path: "{{ mt5_terminals.fivepercent }}"
    display_name: "T5 - Cesar Agusto Lopera Maya"
    account_holder: "{{ account_holder }}"
    prop_firm: "T5"
    initial_balance: 100000.0

  - name: "VPS06-FTMO"
    port: 8002
    terminal_path: "{{ mt5_terminals.ftmo }}"
    display_name: "FTMO - Cesar Agusto Lopera Maya"
    account_holder: "{{ account_holder }}"
    prop_firm: "FTMO"
    initial_balance: 100000.0
