# VPS21 - Sonia Alvarado
vps_name: VPS21
account_holder: "Sonia Alvarado"

agents:
  - name: "VPS21-FundedNext"
    port: 8000
    terminal_path: "{{ mt5_terminals.fundednext }}"
    display_name: "FN - Sonia Alvarado"
    account_holder: "{{ account_holder }}"
    prop_firm: "FN"
    initial_balance: 100000.0

  - name: "VPS21-FivePercent"
    port: 8001
    terminal_path: "{{ mt5_terminals.fivepercent }}"
    display_name: "T5 - Sonia Alvarado"
    account_holder: "{{ account_holder }}"
    prop_firm: "T5"
    initial_balance: 100000.0

  - name: "VPS21-FTMO"
    port: 8002
    terminal_path: "{{ mt5_terminals.ftmo }}"
    display_name: "FTMO - Sonia Alvarado"
    account_holder: "{{ account_holder }}"
    prop_firm: "FTMO"
    initial_balance: 100000.0
